---
title: "Coursework Assignment 1"
author: "Johnny Lee"
date: '28th Sep 2021 '
output:
  html_notebook: default
  pdf_document: default
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(PerformanceAnalytics)
```


```{r}
bloodpressure <- read.table('data/bloodpressure.txt',head=T)
# bloodpressure <- as.data.frame(bloodpressure)
bloodpressure
bp <- bloodpressure$blood_pressure
ld <- bloodpressure$log_drug
rt <- bloodpressure$recovery_time
plot(bp,rt)
plot(ld,rt)
plot(bp, ld)
cor(bloodpressure)
chart.Correlation(bloodpressure)
```
```{r}
min(bp)
max(bp)
```

```{r}
summary(lm(recovery_time ~ log_drug, data=bloodpressure))
```


```{r}
model1 <- lm(recovery_time ~., data=bloodpressure)
summary(model1)
anova(model1)
AIC(model1)
layout(matrix(c(1,3,2,4),2,2))
plot(model1)
```


```{r}
model2 <- lm(recovery_time ~ exp(log_drug) + blood_pressure, data = bloodpressure)
summary(model2)
anova(model2)
AIC(model2)
layout(matrix(c(1,2,3,4),2,2))
plot(model2)
```

```{r}
modellog <- lm(log(recovery_time) ~. , data=bloodpressure)
summary(modellog)
anova(modellog)
layout(matrix(c(1,3,2,4),2,2))
plot(modellog)
```


```{r}
rtreci <- 1/bloodpressure$recovery_time
modelreci <- lm(rtreci ~ log_drug + blood_pressure, data = bloodpressure)
summary(modelreci)
anova(modelreci)
layout(matrix(c(1,3,2,4),2,2))
plot(modelreci)
```

```{r}
modelexp <- lm(exp(recovery_time) ~ log_drug + blood_pressure, data =bloodpressure)
summary(modelexp)
anova(modelexp)
layout(matrix(c(1,3,2,4),2,2))
plot(modelexp)
```

```{r}
modelsqrt <- lm(sqrt(recovery_time)~log_drug + blood_pressure, data = bloodpressure)
summary(modelsqrt)
anova(modelsqrt)
layout(matrix(c(1,3,2,4),2,2))
plot(modelsqrt)
```


```{r}
model3 <- lm(log(recovery_time) ~ exp(log_drug) + blood_pressure, data = bloodpressure)
summary(model3)
anova(model3)
AIC(model3)
layout(matrix(c(1,2,3,4),2,2))
plot(model3)
```

```{r}
newdata <- data.frame(log_drug = 2, blood_pressure = 75)
pi <- predict(modellog, newdata=newdata, interval = "prediction")
print(exp(pi))
```
```{r}
newdata <- data.frame(log_drug = 2, blood_pressure = 75)
pi <- predict(modelsqrt, newdata=newdata, interval = "prediction")
print(pi^2)
```

```{r}
boxplot(bp)$out
boxplot(ld)$out
boxplot(rt)$out
plot(ld,rt)
plot(bp,rt)
```




```{r}
bloodpressure <- bloodpressure[bloodpressure$blood_pressure < min(boxplot(bp)$out),]
bloodpressure <- bloodpressure[bloodpressure$recovery_time < min(boxplot(rt)$out),]
bloodpressure
bp <- bloodpressure$blood_pressure
ld <- bloodpressure$log_drug
rt <- bloodpressure$recovery_time
```



```{r}
par(mfrow=c(2,1))
boxplot(bloodpressure[, "log_drug"] ~ bloodpressure[, "recovery_time"], xlab = "log(drug)", ylab = "Recovery Time", cex.lab=1.5)
boxplot(bloodpressure[, "blood_pressure"] ~ bloodpressure[, "recovery_time"], xlab = "Blood Pressure", ylab = "Recovery Time", cex.lab=1.5)
cor(bloodpressure[,"log_drug"], bloodpressure[,"recovery_time"])
cor(bloodpressure[,"blood_pressure"], bloodpressure[,"recovery_time"])
```

